name: CICD
on: [push, workflow_dispatch]
jobs:
  cicd:
    uses: internetarchive/cicd/.github/workflows/cicd.yml@main
    runs-on: self-hosted
    permissions: { contents: read, packages: write, id-token: write }
    with:
      BASE_DOMAIN: 'nn.starnix.net'
      NOMAD_ADDR: 'http://nn.starnix.net:4646'
      REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  secrets:
    NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}

