name: CI/CD build, test and deploy using github registry and nomad

on:
  workflow_call:
    secrets:
      NOMAD_TOKEN:
        description: 'Nomad cluster credentials'
        required: false
    inputs:
      PLATFORMS:
        description: 'Platforms for building'
        required: false
        type: string
        default: 'linux/amd64'
      BASE_DOMAIN:
        description: 'Nomad cluster wildcard DNS domain name'
        required: false
        type: string
        default: 'dev.archive.org'
      TEST_SCRIPT:
        description: 'Test script path'
        required: false
        type: string
        default: './test.sh'
env:
  IMG: ghcr.io/${{ github.repository }}:${{ github.ref_name }}

jobs:
  build:
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build and push image
        run: |
          echo "Building Docker image"
          docker build -t ${{env.IMG}} .
          docker push ${{env.IMG}}
    outputs:
      imgworkdir: '/app'

  test:
    needs: build
    container:
      image: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
    steps:
      - name: Run tests
        working-directory: ${{ needs.build.outputs.imgworkdir }}
        run: ${{ inputs.TEST_SCRIPT }}

  deploy:
    needs: test
    container:
      image: docker://registry.gitlab.com/internetarchive/nomad/master
      env:
        BASE_DOMAIN: ${{ inputs.BASE_DOMAIN }}
        NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
    steps:
      - name: Deploy
        run: /deploy.sh
